### ISSUE TITLE
Source.waitReady() method stuck on  HP MF1530

### ISSUE THREAD

**Issue by peihexian** [xricht17/twpp#20]
in windows 10 and HP MF1530, there are some issues with the following code execution

    Twpp::Handle hwd=Twpp::Handle();
    userSrc.enable(UserInterface(true, true, hwd));
    userSrc.waitReady();   //The scan is actually completed when it is executed here, but it is never returned

does anyone  provide some ideas for solving the problem?

**Comment by xricht17** [comment]
Hi,

My bet is on the window handle `hwd` that you pass to `UserInterface` and the `enable` method. I am not sure if window events are processed correctly in `waitReady` when a `null` or invalid window handle is used. Try a valid window, e.g. create a dummy hidden window, and pass its handle to `UserInterface`.

**Comment by peihexian** [comment]
I found the cause of the problem, because the HP driver only supports the old-fashioned TWAIN_32.dll mode, the support for TWAINDSM.dll is not good enough, thank you for your reply!
