### ISSUE TITLE
MSVC 2017 linkage issue

### ISSUE THREAD

**Issue by neklesayurii** [xricht17/twpp#21]
Hi
I had no problems building project with MinGW 7.3.0.
But had linker issues building it with MSVC 2017. Fixed it by linking to **user32.lib** manually.
Found solution [here](http://www.cplusplus.com/forum/windows/19865/)
Consider adding this step to readme

**Comment by xricht17** [comment]
Hi, I have added `user32.lib` to Windows requirements in the README. Thanks for letting me know about this!
