### ISSUE TITLE
Creat Range type error

### ISSUE THREAD

**Issue by CrisisPeng** [xricht17/twpp#22]
hello! i'm trying to creat a range type cap,such as IBrightness,  while using the createRange  method to creat range type, occured  error((In TWAIN_App_mfc32.exe) Thrown by exception: 0xC0000005: An access violation occurred while reading location 0x7C1D45DB.)! below is the code i was wrote, please point out is there  something wrong i made.thank you!
```
    m_query[CapType::IBrightness] = msgSupportGetAllSetReset;
    m_caps[CapType::IBrightness] = [this](Msg msg, Capability& data)->Result {
        switch (msg) {
        case Msg::Get:
                data = Capability::createRange<CapType::IBrightness>(Fix32(-1000.0f),
                    Fix32(1000.0f),
                    Fix32(333.0f),
                    m_brightness,
                    Fix32(0.0f));             
            return success();
        case Msg::Reset:
            m_brightness =0.0f;
            return success();
        case Msg::GetCurrent:
            data = Capability::createOneValue<CapType::IBrightness>(m_brightness);
            return success();
        case Msg::GetDefault:
            data = Capability::createOneValue<CapType::IBrightness>(Fix32(0.0f));
            return success();
        case Msg::Set: {
            auto mech = data.currentItem<CapType::IBrightness>();
            m_brightness = (float)mech;
            return success();
        }
        default:
            return capBadOperation();
        }
    };
```

**Comment by xricht17** [comment]
Hi,

This is DS flavour, and you changed the example DS a bit, right? I can't see anything wrong with your snippet.

However, I noticed that [`Capability::createRange`](https://github.com/xricht17/twpp/blob/b612fbf9db29fb71ea629bdacf18ebb6500be227/twpp/capability.hpp#L1541) in `capability.hpp` uses `sizeof(Detail::OneValueData<DataType>)` instead of `sizeof(Detail::RangeData<DataType>)`. Could you change it on your side, and see what happens?

**Comment by CrisisPeng** [comment]
thanks for your reply，as what you said, i used sizeof(Detail::OneValueData<DataType>) instead of sizeof(Detail::RangeData<DataType>),while  occuered error again.

**Comment by xricht17** [comment]
Hmm. I have just tried your snippet with the example DS (MinGW-W64 GCC 5.3.0, Qt 5.11.1 32bit). It works for me with and without the fix I mentioned earlier. When you copied the resulting `.ds` file to your `\Windows\twain_32` directory, did you make sure it contained all the necessary DLLs?

E.g. for me it were these files, as I used MinGW compiler and debug version of Qt: `libgcc_s_dw2-1.dll`, `libstdc++-6.dll`, `libwinpthread-1.dll`, `Qt5Cored.dll`, `Qt5Guid.dll`, `Qt5Widgetsd.dll`.

You can also try using TWACKER to help with debugging of your DS https://developer.dynamsoft.com/dwt/kb/2644.

**Comment by CrisisPeng** [comment]
I am sure i have put all  the necessary  dlls in the \Windows\twain_32 directory,without the Range type caps,it works well.
As you noticed,i change the type to RangeData,it works well by the TWACKER app,while the TWAIN Sample App it can not  show the proper Range type values,the values are empty.a bit strange.
By the way,i implement TWAIN UI by MFC,do it matter?

**Comment by xricht17** [comment]
32bit TWAIN Sample App v2.3 from https://sourceforge.net/projects/twain-samples/files/TWAIN%202%20Sample%20Application/ works fine for me. It does not support setting ranges, but it shows the current value properly. Is this the app/version you are using?

Inspector Twain (http://www.inspectortwain.com/installer.aspx) found 2 errors in your code:
- `Msg::Reset` must also return the reset value in the same manner as `Msg::GetCurrent`. A simple fallthrough should be enough here.
- You do no check bounds in `Msg::Set`. If the value is outside of <-1000; 1000>, you need to return `badValue()`.

UI framework should not matter as long as the parts are properly glued together.

**Comment by CrisisPeng** [comment]
Yes,i am  using the 32bit TWAIN Sample App v2.3 .thank you very much,i ma going to fix the incorrect caps i wrote.
To be honest,the twain datasource architecture is so smart.thank you .
