### ISSUE TITLE
Call Source.enable() with showUI = false don't set m_readyMsg to Msg::XferReady

### ISSUE THREAD

**Issue by craxycat** [xricht17/twpp#25]
When call 
`src.enable(UserInterface(false, false, Handle())); // showUI = false `
callback don't set m_readyMsg to Msg::XferReady, because checking m_state == DsState::Enabled before m_state setted to this state.
Line 860 in application.hpp:
```
if (src->m_state == DsState::Enabled){
            src->m_readyMsg = msg;
```

**Comment by xricht17** [comment]
Hi craxycat,

Thanks for the issue report! Let me see what I can do about it.

**Comment by xricht17** [comment]
It should be fixed now. Could you test it on your end?

**Comment by craxycat** [comment]
Yes, it's fixed now. Thank you!
