### ISSUE TITLE
about datasource memerxfer bug

### ISSUE THREAD

**Issue by CrisisPeng** [xricht17/twpp#29]
hi!
i found that there is a problem about memoryxfer mode，if transfer RGB bitmap，it's ok，while in Gray or BlackWhite bitmap data,it is unnecessary to switch channels for Red and Blue channel。
			//BGR BMP -> RGB memory transfer
			for (; line + 3 < out; line += 3) {
				std::swap(line[0], line[2]);
			}

**Comment by xricht17** [comment]
Hi.

The example DS does not support anything besides the most basic RGB BMP, e.g. RLE-compressed BMPs will most likely fail miserably. It is not meant as a building block for any production stuff - it is just an example on how `TWPP` can be used for source development.

**Comment by CrisisPeng** [comment]
ok，i got it.tks.
