### ISSUE TITLE
Complete Mac OS support

### ISSUE THREAD

**Issue by xricht17** [xricht17/twpp#3]
Test TWPP on Mac OS, both application and data  source. Fix platform-specific issues.

**Comment by kwach** [comment]
+1

(right now it won't compile for me on including deprecated MacMemory.h)

**Comment by xricht17** [comment]
Hi kwach, 

The TWAIN 2.4 specification itself (http://www.twain.org/specification/ > Files > TWAIN 2.4 Specification) dictates in chapter 12-8 > _Memory Management in TWAIN_ that both application and source must use `NewHandle` and `DisposeHandle` functions for memory allocation and deallocation respectively, when these operations are not supplied by the Source Manager. These functions are found in the deprecated file `MacMemory.h` which is available for support of legacy applications, in this case old TWAIN framework.

Use of deprecated stuff usually results in a warning during compilation, not an error. Check your compiler parameters and make sure there is no parameter that upgrades simple warnings to errors, or add a one to ignore this particular warning/error.

**Comment by kwach** [comment]
Perhaps you could help me running it then?

After including the header and figuring out to copy MacMemory.h into the project I have issue locating type DsmEntry

In file included from project/src/handler.cpp:3:
In file included from project/src/twpp/../twpp.hpp:30:
project/src/twpp/env.hpp:159:19: error: unknown type name 'DsmEntry'

I’ll update the README.md with all the details if I succeed :)

Best regards,
M.

**Comment by xricht17** [comment]
Yeah, looks like I forgot to change the function `Twpp::Detail::DsmLibOs::resolve` for Mac OS and Linux in `twpp/env.hpp` in the same way I did for the Windows version in commit 89f14e41ed6229950a6a5d2b510712ccb4519cbf.

The bug is tracked in issue #6.

**Comment by kwach** [comment]
OK!

That fixed the compilation. I’ll craete pull request shortly. :)

Pozdrawiam,
M.
