### ISSUE TITLE
Bug: with Detail::Range container iterator compare !=

### ISSUE THREAD

**Issue by adam-seychell** [xricht17/twpp#31]
When recently trying to iterate through a Detail::Range container I found it would fail because the != and == operators on iterators would return same value. A simple negatation fixed it as follows.

File: capability.cpp  
Line 727
```
        bool operator!=(const IteratorImpl& o) const noexcept{
            return !(*this == o);                                       // FIXED: negated added to expression
        }

```

**Comment by xricht17** [comment]
Hi @adam-seychell, thanks for the report. You are 100 % correct, there's a missing negation there. It should be fixed now.
