### ISSUE TITLE
Support higher versions of macOs and Ubuntu ？

### ISSUE THREAD

**Issue by peng-kid** [xricht17/twpp#32]
Can it support higher versions of macOs and Ubuntu, any comments?

I tested it on macOs12 and Ubuntu20.4 and it doesn't work.

The problem is with the Manager::load method. I checked the system directory, there is no dynamic library, such as libtwaindsm.so .

**Comment by xricht17** [comment]
Hi @pengkid-rgb,

TWAIN is mainly Windows library, and even there [WIA](https://docs.microsoft.com/en-us/windows/win32/wia/-wia-startpage) seems to be the preferred option.

Linux distributions do not come with TWAIN preinstalled, you'd have to download and install its dynamic library manually. Even if you do install it, I doubt you will find many device drivers for Linux. Look into [SANE](http://www.sane-project.org/) instead.

As for Mac OSX, IIRC, they dropped TWAIN support entirely in 10.15.0 in favour of [Image Capture](https://support.apple.com/guide/image-capture/).

**Comment by peng-kid** [comment]
OK, thanks. I've decided to switch to SANE!
