### ISSUE TITLE
An error was reported when transmitting pictures

### ISSUE THREAD

**Issue by EricsZhou** [xricht17/twpp#33]
Hello, I use a test software, and the picture transferred by your example program can be successfully transferred to the test software.  However, it fails to be displayed when I replace your picture resources.  Do you have any good methods?
![image](https://user-images.githubusercontent.com/94219246/187816813-9c814883-d60b-418f-8762-916de790f6c0.png)

**Comment by xricht17** [comment]
Hi @EricsZhou,

Do you mean the [example simple DS](https://github.com/xricht17/twpp/tree/master/examples/simpleds)? It is not meant to be production-ready, but to merely help you learn source development with `twpp`.

With that said, you are more than welcome to submit a merge request to fix any bug you might find, or provide a bug report and someone else will have a look. We will need a bit more information if we are to hunt this bug, though.

**Comment by EricsZhou** [comment]
@xricht17 Thank you very much for your reply. I used a tool to capture his print information, the message is that the input data is corrupt, should be qUncompress step error.Below are some of the printouts I've taken
![image](https://user-images.githubusercontent.com/94219246/188037025-5e9d79ac-7137-415f-bdef-ed2294b48df1.png)

**Comment by EricsZhou** [comment]
I have never understood why the qUncompress step is done. If this step is necessary, I wonder if there is any other way to implement it

**Comment by xricht17** [comment]
Oh, now I understand. That's related to Qt framework, and how it handles resources (data embedded inside the executable itself).

The project file `simpleds.pro` defines resource files - we only have `images.qrc` there. In `images.qrc`, you can find what files will be embedded inside the executable, and hence available using `QResource`. Resource data is compressed, so `qUncompress` is used. There was no [QResource::uncompressedData](https://doc.qt.io/qt-6/qresource.html#uncompressedData) when I built that example for Qt4.

I expect you did not include your image file in `images.qrc`, so it is not available as a resource. `QResource` is then empty, and nothing is passed into `qUncompress`, which returns empty result. Or your `QResource` uses a different compression algorithm from what `qUncompress` is able to handle.

**Comment by xricht17** [comment]
No response for 9 days -> closing.
