### ISSUE TITLE
How do I set scan properties

### ISSUE THREAD

**Issue by JCCVW** [xricht17/twpp#37]
Hello, thank you very much for your work. I would like to ask you a question. I want to use twain to set scanner attributes, such as length, width, color, scanning mode, etc. How to operate this? Could you please give me a simple example? The official pdf seems to send specific instructions, but I don't know what the corresponding instruction is for a certain attribute of my current scanner. I am looking forward to your reply very much

**Comment by xricht17** [comment]
Hi @JCCVW,

If I understand you correctly, then your question is about the TWAIN protocol itself, not TWPP. As TWPP is just a thin layer over TWAIN itself, it would be best to ask this question on TWAIN support forums, or read the TWAIN manual more thoroughly.

With that said, let me give you a few pointers. Most image properties are set up through **capabilities**. There's a whole chapter about them in the TWAIN manual, including their listing and description of each one. Some others, like **image layout**, are handled by dedicated operations. [TWAIN sample application](https://github.com/twain/twain-samples) is an excellent way to see all of that in action.
