### ISSUE TITLE
How to set JPEGQUALITY ?

### ISSUE THREAD

**Issue by moonofmars** [xricht17/twpp#38]
tried 

MyCapability(src, Msg::Set, Capability::createOneValue<CapType::ICompression>(Compression::Jpeg));

then

MyCapability(src, Msg::Set, Capability::createOneValue<CapType::IJpegQuality>(JpegQuality::Low));

but useless.

**Comment by xricht17** [comment]
Hi @moonofmars,

What exact issue do you have with TWPP? TWPP is a thin C++ wrapper around the plain C TWAIN API. As such, there is a good chance that you misunderstood something about TWAIN, and not that there is a bug in TWPP.

Also, please do give more context, and generally invest more time and effort when asking questions.
