### ISSUE TITLE
I want to build a scanner app,But I dont know how to set up XResolution.

### ISSUE THREAD

**Issue by TOOGO404** [xricht17/twpp#39]
Look,I have Get the enumerations about IXResolution.But I dont konw  how to create Enumeration With Fix32 type.
![image](https://github.com/xricht17/twpp/assets/102414197/65ab1274-a4c0-4e4f-83e6-c84c94c735c4)

**Comment by xricht17** [comment]
Hi, I am not sure what the question is. You already seem to have `Fix32 Enumeration`, since `IXResolution` maps to `Fix32` type.

**Comment by TOOGO404** [comment]
I've solved that problem now, but I'm running into another issue, I had set the duplex capability to true successfully, when I call Transfer Image at the second time, the call fails. Can you give me an example of a TWAIN app to get a duplex scanned image?
![image](https://github.com/xricht17/twpp/assets/102414197/3d82c456-bb09-40c3-b297-59d4fdf247df)
![image](https://github.com/xricht17/twpp/assets/102414197/26f2af30-278c-4849-aec1-87a7a31a33c8)

**Comment by xricht17** [comment]
One obvious issue that I can see in your code is that you are _getting_ the duplex capability state, not _setting_ it (`Msg::Get` vs `Msg::Set`). It would also be easier to use `OneValue` instead `Enumeration` to set a simple boolean value.

As for properly setting up duplex scanning, I am afraid I can't help you as I have never done it myself. I'll have to direct you to the TWAIN manual, or their forums.
