### ISSUE TITLE
Compiling with Visual Studio 2015 on Windows 10 Error out: "std::copy::_Unchecked_iterators::_Deprecate"

### ISSUE THREAD

**Issue by Needo** [xricht17/twpp#5]
Severity    Code    Description Project File    Line    Suppression State
Error   C4996   'std::copy::_Unchecked_iterators::_Deprecate': 
Call to 'std::copy' with parameters that may be unsafe - 
this call relies on the caller to check that the passed values are correct. 
To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. 
See documentation on how to use Visual C++ 'Checked Iterators'  
TWANDSDemo  
c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility 2322

**Comment by xricht17** [comment]
This is most likely due to `StatusUtf8` (status.hpp) constructors using `std::copy` to copy a character array. You can safely ignore this VS-specific warning using that cmd parameter you posted or with pragmas.

**Comment by Needo** [comment]
Yes, it was warning but it was presenting as error due to project being set "SDL checks = Yes (/sdl)"
Turning off  "SDL checks =No (/sdl-)" allowed successful compilation, its explained here:
http://stackoverflow.com/questions/33057834/how-to-disable-a-warning-in-visual-studio-2015-for-c

Thanks for pointing out correct direction for fix!
