### ISSUE TITLE
Memory Xfer hangs

### ISSUE THREAD

**Issue by kwach** [xricht17/twpp#9]
Hi there,

I think I found an error. When memory transfer is chosen after enabling the source a wait must occur for XferReady signall. 

Below code would hang on `waitReady`

```
               Twpp::Capability xferMech = Twpp::Capability::createOneValue<Twpp::CapType::IXferMech>(Twpp::XferMech::Memory);
		ret = src.capability(Twpp::Msg::Set, xferMech);
		
		ret = src.enable(Twpp::UserInterface(false, false, Twpp::Handle()));

		ret = src.waitReady();

```

Only after chaning the following piece in application.hpp:295 it goes flowlessly forward. I've tested this only on Windows, where there are no callbacks.

```c++
auto rc = dsm(DataGroup::Control, Dat::Event, Msg::ProcessEvent, event);
            switch (rc){
                case ReturnCode::NotDsEvent:
                    TranslateMessage(&msg);
                    DispatchMessage(&msg);
                    // fallthrough
                case ReturnCode::DsEvent:
                    //if (!usesCb){ //MK> I won't break this loop otherwise
                        d()->m_readyMsg = event.message();
                    //}

                    break;

                default:
                    return rc;
            }
```

Am I doing this wrong or there is an actual issue here?

**Comment by xricht17** [comment]
Hi,

Windows will use callbacks since TWAIN v2 (or around that version). Looks like the callback got registered but somehow the DS did not properly invoke it? I guess setting the message in event loop, even when the callback is registered, can't really hurt anything - it will actually add a bit more robustness. Could you fix the indentation and create a pull request? Thanks!

**Comment by kwach** [comment]
Will do.

**Comment by xricht17** [comment]
BTW there is also `processEvent` that needs the same modification. I am thinking if we should overwrite `d()->m_readyMsg` only if it is `Msg::Null`, and leave it be otherwise. Also, `usesCb` will only be used in non-Windows version of `waitReady`, and not at all in `processEvent`.

**Comment by xricht17** [comment]
This issue should be resolved now. Please verify.
